version: '1.0'

services:
  postgres:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_DB: task_management
      POSTGRES_USER: user_management
      POSTGRES_PASSWORD: managementpass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  springboot:
    image: openjdk:17
    container_name: springboot-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/task_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - ./target:/app
    command: ["java", "-jar", "/app/task-management-0.0.1.jar"]
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge